services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - rag.env
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5500:80"
    env_file:
      - rag.env
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge